package com.example.OzonHelper.enums;

public enum SupplyDraftCreateErrorMessage {
    UNSPECIFIED("UNSPECIFIED"),
    EMPTY_ITEMS_LIST("EMPTY_ITEMS_LIST"),
    ITEMS_COUNT_MORE_THAN_MAX("ITEMS_COUNT_MORE_THAN_MAX"),
    UNKNOWN_CLUSTER_IDS("UNKNOWN_CLUSTER_IDS"),
    ITEMS_VALIDATION("ITEMS_VALIDATION"),
    DROP_OFF_POINT_DOES_NOT_EXIST("DROP_OFF_POINT_DOES_NOT_EXIST"),
    DROP_OFF_POINT_HAS_NO_TIMESLOTS("DROP_OFF_POINT_HAS_NO_TIMESLOTS"),
    TOTAL_VOLUME_IN_LITRES_INVALID("TOTAL_VOLUME_IN_LITRES_INVALID"),
    SKU_DISTRIBUTION_REQUIRED_BUT_NOT_POSSIBLE("SKU_DISTRIBUTION_REQUIRED_BUT_NOT_POSSIBLE"),
    CROSS_DOCK_IN_DELIVERY_POINT_DISABLED_FOR_SELLER("CROSS_DOCK_IN_DELIVERY_POINT_DISABLED_FOR_SELLER"),
    DUPLICATE_SKUS_IN_REQUEST("DUPLICATE_SKUS_IN_REQUEST"),
    CAN_NOT_CREATE_DRAFT("CAN_NOT_CREATE_DRAFT"),
    DRAFT_TOTALS_INVALID_ERROR("DRAFT_TOTALS_INVALID_ERROR"),
    CAN_NOT_START_CALCULATION("CAN_NOT_START_CALCULATION"),
    PICKUP_IS_NOT_AVAILABLE("PICKUP_IS_NOT_AVAILABLE"),
    DROP_OFF_NOT_COMPATIBLE_WITH_PICKUP("DROP_OFF_NOT_COMPATIBLE_WITH_PICKUP"),
    UNDEFINED("UNDEFINED");

    private final String apiValue;

    SupplyDraftCreateErrorMessage(String apiValue) {
        this.apiValue = apiValue;
    }
    }
