package com.example.OzonHelper.enums;

public enum SupplyCreateRejectedItemReason {
    UNSPECIFIED("UNSPECIFIED"),
    OUT_OF_ASSORTMENT("OUT_OF_ASSORTMENT"),
    INVALID("INVALID"),
    INCOMPATIBLE_WAREHOUSE("INCOMPATIBLE_WAREHOUSE"),
    EMPTY_BARCODE("EMPTY_BARCODE"),
    EMPTY_PS_ATTRIBUTE("EMPTY_PS_ATTRIBUTE"),
    MULTIPLICITY("MULTIPLICITY"),
    NO_PRICE("NO_PRICE"),
    INVALID_ITEM_COUNT_MAX("NO_PRICE"),
    INVALID_ITEM_COUNT_ZERO("INVALID_ITEM_COUNT_ZERO"),
    SKU_REJECTED_BY_ACCEPTANCE_RESTRICTIONS("SKU_REJECTED_BY_ACCEPTANCE_RESTRICTIONS"),
    SKU_WITH_ETTN_REQUIRED_TAG_NOT_ALLOWED("SKU_WITH_ETTN_REQUIRED_TAG_NOT_ALLOWED"),
    SKU_WITOUT_ETTN_REQUIRED_TAG_NOT_ALLOWED("SKU_WITOUT_ETTN_REQUIRED_TAG_NOT_ALLOWED"),
    SKU_WITH_TRACEABLE_TAG_NOT_ALLOWED("SKU_WITH_TRACEABLE_TAG_NOT_ALLOWED"),
    SKU_IS_RESTRICTED("SKU_IS_RESTRICTED"),
    EMPTY_CLUSTER("EMPTY_CLUSTER"),
    SKU_WITH_UTD_REQUIRED_TAG_NOT_ALLOWED("SKU_WITH_UTD_REQUIRED_TAG_NOT_ALLOWED"),
    CORRUPTED_ASSORTMENT("CORRUPTED_ASSORTMENT"),
    STORAGE_BELARUS_SKU_HAS_NO_SELLER_FEACN("STORAGE_BELARUS_SKU_HAS_NO_SELLER_FEACN"),
    TRACEABLE_SKU_HAS_NO_GTIN_BARCODE("TRACEABLE_SKU_HAS_NO_GTIN_BARCODE"),
    TRACEABLE_SKU_HAS_NO_MEASUREMENT_UNIT_QUANTITY("TRACEABLE_SKU_HAS_NO_MEASUREMENT_UNIT_QUANTITY"),
    SKU_HAS_INVALID_HS_CODE("SKU_HAS_INVALID_HS_CODE"),
    SKU_HAS_STORAGE_COUNTRY_RESTRICTIONS("SKU_HAS_STORAGE_COUNTRY_RESTRICTIONS"),
    UNDEFINED("UNDEFINED");

    private final String apiValue;

    SupplyCreateRejectedItemReason(String apiValue) {
        this.apiValue = apiValue;
    }
}
