package com.example.OzonHelper.enums.ozon;

public enum SupplyCreateErrorReason {
    UNSPECIFIED("UNSPECIFIED"),
    SOME_SERVICE_ERROR("SOME_SERVICE_ERROR"),
    ORDER_SKU_LIMIT("ORDER_SKU_LIMIT"),
    INVALID_QUNATITY_OR_QUANT("INVALID_QUANTITY_OR_QUANT"),
    ORDER_ALREADY_CREATED("ORDER_ALREADY_CREATED"),
    ORDER_CREATION_IN_PROGRESS("ORDER_CREATION_IN_PROGRESS"),
    DRAFT_DOES_NOT_EXIST("DRAFT_DOES_NOT_EXIST"),
    CONTRACTOR_CAN_NOT_CREATE_ORDER("CONTRACTOR_CAN_NOT_CREATE_ORDER"),
    INACTIVE_CONTRACT("INACTIVE_CONTRACT"),
    DRAFT_INCORRECT_STATE("DRAFT_INCORRECT_STATE"),
    INVALID_VOLUME("INVALID_VOLUME"),
    INVALID_ROUTE("INVALID_ROUTE"),
    INVALID_STORAGE_WAREHOUSE("INVALID_STORAGE_WAREHOUSE"),
    INVALID_STORAGE_REGION("INVALID_STORAGE_REGION"),
    INVALID_SPLITTING("INVALID_SPLITTING"),
    INVALID_SUPPLY_CONTENT("INVALID_SUPPLY_CONTENT"),
    TIMESLOT_NOT_AVAILABLE("TIMESLOT_NOT_AVAILABLE"),
    SKU_DISTRIBUTION_REQUIRED_BUT_NOT_POSSIBLE("SKU_DISTRIBUTION_REQUIRED_BUT_NOT_POSSIBLE"),
    XDOCK_IN_DELIVERY_POINT_DISABLED_FOR_SELLER("XDOCK_IN_DELIVERY_POINT_DISABLED_FOR_SELLER"),
    DRAFT_IS_LOCKED("DRAFT_IS_LOCKED"),
    INVALID_PACKAGE_UNITS_COUNT("INVALID_PACKAGE_UNITS_COUNT"),
    SELLER_CONVERSATION_DOES_NOT_EXIST("SELLER_CONVERSATION_DOES_NOT_EXIST"),
    USER_CAN_NOT_CREATE_SELLER_CONVERSATION("USER_CAN_NOT_CREATE_SELLER_CONVERSATION"),
    SKU_WITH_ETTN_REQUIRED_TAG_NOT_ALLOWED_FOR_DROP_OFF_POINT("SKU_WITH_ETTN_REQUIRED_TAG_NOT_ALLOWED_FOR_DROP_OFF_POINT"),
    INVALID_SELLER_WAREHOUSE("INVALID_SELLER_WAREHOUSE"),
    PICKUP_ORDER_LIMIT_EXCEED("PICKUP_ORDER_LIMIT_EXCEED"),
    MINIMUM_VOLUME_IN_LITRES_INVALID("MINIMUM_VOLUME_IN_LITRES_INVALID"),
    INVALID_CLUSTERS_COUNT("INVALID_CLUSTERS_COUNT"),
    CAN_NOT_CREATE_ORDER("CAN_NOT_CREATE_ORDER"),
    UNDEFINED("UNDEFINED");

    private final String apiValue;

    SupplyCreateErrorReason(String apiValue) {
        this.apiValue = apiValue;
    }
}
